; Common settings that apply to both the Tag and Anchor
[env]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
board_upload.speed = 115200
monitor_speed = 115200
lib_deps = https://github.com/Makerfabs/Makerfabs-ESP32-UWB-DW3000

; ---------- Environment 1: The Tag (Initiator) ----------
[env:tag]
; This tells PIO to ONLY compile tag.cpp and ignore anchor.cpp
build_src_filter = +<tag.cpp> -<anchor.cpp>

; ---------- Environment 2: The Anchor (Responder) -------
[env:anchor]
; This tells PIO to ONLY compile anchor.cpp and ignore tag.cpp
build_src_filter = +<anchor.cpp> -<tag.cpp>